### ISSUE TITLE
Invalid link for systemd-networkd documentation

### ISSUE THREAD

**Issue by rr-santos** [bisdn/bisdn.github.io#30]
In the first paragraph of [Persisting network configuration](https://docs.bisdn.de/setup/setup_standalone.html#persisting-network-configuration), there is a broken reference for `systemd-networkd`, i.e.: 
> :ref:”systemd-networkd” 

Both first and second paragraphs should be rewritten, in addition to fixing the broken link.

**Comment by hilmarm** [comment]
This has been fixed, the link works in branch 'revised-docs'
