### ISSUE TITLE
FRR section missing from tools

### ISSUE THREAD

**Issue by hilmarm** [bisdn/bisdn.github.io#40]
Listed among the tools bundled with the switch image is FRR
https://docs.bisdn.de/setup/setup_standalone.html#frrouting

Our revised-docs seems to be missing this. This would belong in the 'Tools' section.

**Comment by jklare** [comment]
not sure if this belongs into the tools section our should be just mentioned in the corresponding examples

**Comment by hilmarm** [comment]
#49 fixes this issue, as it mentions FRR and refers to FRR documentation in the examples.
