### ISSUE TITLE
OFDPA-related documentation not listed

### ISSUE THREAD

**Issue by rr-santos** [bisdn/bisdn.github.io#43]
In [Basebox/OpenFlow](https://docs.bisdn.de/basebox.html#openflow), it is listed that table type specification guidelines are available, but there is no link or additional information on where to find them. Adding such link would make it more clear on these guidelines.

Similarly, a link for OF-DPA could be nice to have here when mentioning "Broadcom OF-DPA".

**Comment by hilmarm** [comment]
afaik the specifications for of-dpa 2.0 are available on https://github.com/Broadcom-Switch/of-dpa/blob/master/OFDPAS-ETP100-R.pdf
the reference manual can be found here: http://broadcom-switch.github.io/of-dpa/doc/html/pages.html
