### ISSUE TITLE
Reference to ipv6 addresses that are public.

### ISSUE THREAD

**Issue by hilmarm** [bisdn/bisdn.github.io#67]
https://docs.bisdn.de/network_configuration/static_routing.html#iproute2-1, https://docs.bisdn.de/network_configuration/ospf.html#ospfv3 and https://docs.bisdn.de/network_configuration/bgp.html#bgp-for-ipv6-networks configure networks with ipv6 address a 2003 prefix. This prefix seems to be meant for reservation (Telekom has 2003:: /19 for example.

Should these be changed to a private range like

**Comment by jklare** [comment]
These can be aligned with the ones used in the testing pipeline, which are taken from the ipv6 documentation blocks
